### ISSUE TITLE
ugettext_lazy` was deprecated in v2.2 and no longer used in django v3+.

### ISSUE THREAD

**Issue by vizvasrj** [iarp/django-taggit-autosuggest#1]
```
    from taggit_autosuggest.widgets import TagAutoSuggest
  File "/root/Project/zoo/mul/lib/python3.9/site-packages/taggit_autosuggest/widgets.py", line 10, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/root/Project/zoo/mul/lib/python3.9/site-packages/django/utils/translation/__init__.py)


```

**Comment by iarp** [comment]
Are you certain you're using my repo for the library? We're not using ugettext_lazy: https://github.com/iarp/django-taggit-autosuggest/blob/master/taggit_autosuggest/widgets.py#L6

If you're using it from pypi then that repo is here: https://bitbucket.org/fabian/django-taggit-autosuggest/src/master/ I forked this repo from them but github doesn't link back to bitbucket like that for forks

**Comment by vizvasrj** [comment]
Is this nOt Yours?

**Comment by vizvasrj** [comment]
Sorry

**Comment by iarp** [comment]
Not a problem. I am not the owner of `pip install django-taggit-autosuggest` that belongs to someone else and that seems to be where your error comes from. This repo is mine which I forked from the original library and updated to my own needs.
