### ISSUE TITLE
how to use inside Django Admin

### ISSUE THREAD

**Issue by lsmith77** [iarp/django-taggit-autosuggest#2]
Please advise what the best approach is for using inside Django Admin?

https://github.com/iarp/django-taggit-autosuggest#usage

**Comment by iarp** [comment]
There shouldn't be anything necessary above adding the field to admin fieldsets if you've defined fieldsets. The documentation in Usage is there for use on your own forms and views.

**Comment by lsmith77** [comment]
ok. thank you for the feedback. it didn't seem to work for me and I have now switched to https://django-autocomplete-light.readthedocs.io/en/master/
